# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 20:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Thoughts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user1', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
